// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwarjcWu1fYIcAPlhW5ZPk0ij1h7Hj_vc',
    appId: '1:900992527109:web:8cb498c94d7ee4bdea656c',
    messagingSenderId: '900992527109',
    projectId: 'meetup2-f77d4',
    authDomain: 'meetup2-f77d4.firebaseapp.com',
    storageBucket: 'meetup2-f77d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcP0iuY7Gj23rEr4tMjq1TFWUOG4MT36M',
    appId: '1:900992527109:android:4f33c6a21601a423ea656c',
    messagingSenderId: '900992527109',
    projectId: 'meetup2-f77d4',
    storageBucket: 'meetup2-f77d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAicDbiLVWWZXe3QCwEyrMMxsgp2YYhDr8',
    appId: '1:900992527109:ios:71364daa886a9f1dea656c',
    messagingSenderId: '900992527109',
    projectId: 'meetup2-f77d4',
    storageBucket: 'meetup2-f77d4.appspot.com',
    iosBundleId: 'com.example.connect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAicDbiLVWWZXe3QCwEyrMMxsgp2YYhDr8',
    appId: '1:900992527109:ios:71364daa886a9f1dea656c',
    messagingSenderId: '900992527109',
    projectId: 'meetup2-f77d4',
    storageBucket: 'meetup2-f77d4.appspot.com',
    iosBundleId: 'com.example.connect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwarjcWu1fYIcAPlhW5ZPk0ij1h7Hj_vc',
    appId: '1:900992527109:web:c992104c1054a624ea656c',
    messagingSenderId: '900992527109',
    projectId: 'meetup2-f77d4',
    authDomain: 'meetup2-f77d4.firebaseapp.com',
    storageBucket: 'meetup2-f77d4.appspot.com',
  );

}